#!/bin/bash
PATH=./node_modules/.bin:$PATH
ENTRIES_GLOB="./src/entries/**/*.{js,css}"
PARCEL_GLOB="./_dist/**/*.html"

function install {
    yarn
}

function clean {
  rm -rf dist _dist .parcel-cache .cache
}

function build {
    cross-env ELEVENTY_ENV=prod eleventy --output _dist && parcel build ${PARCEL_GLOB}
}

function stage() {
  build && lite-server --baseDir="dist"
}

function start {
    dev
}

function dev {
  dev:eleventy &
  dev:parcel &
  wait
}


function dev:eleventy {
  cross-env ELEVENTY_ENV=dev eleventy --watch --output _dist
}

function dev:parcel {
  parcel ${PARCEL_GLOB}
}

function default {
    install && start
}

function help {
  echo "source $0"
  echo "run <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

if [[ "$0" = "$BASH_SOURCE" ]]; then
  TIMEFORMAT="Task completed in %3lR"
  time ${@:-default}
else
  alias run=./Taskfile
fi
