#!/bin/bash
PATH=./node_modules/.bin:$PATH
ENTRIES_GLOB="./src/entries/**/*.{js,css}"

function install {
    yarn
}

function build {
    cross-env ELEVENTY_ENV=prod eleventy && parcel build ${ENTRIES_GLOB}
}

function start {
    dev
}

function dev {
  dev-eleventy & dev-parcel
}

function dev-eleventy {
  cross-env ELEVENTY_ENV=dev eleventy --serve
}

function dev-parcel {
  parcel watch --no-hmr ${ENTRIES_GLOB}
}

function default {
    install && start
}

function help {
  echo "source $0"
  echo "run <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

if [[ "$0" = "$BASH_SOURCE" ]]; then
  TIMEFORMAT="Task completed in %3lR"
  time ${@:-default}
else
  alias run=./Taskfile
fi
